package ATM;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Denzel
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    Connection con;
    Statement stmt;
    ResultSet rs;
    int curRoiw=0;
    public MainMenu() {
        initComponents();
        doConnect();
    }
    public void doConnect(){
    try{
       String host="jdbc:derby://localhost:1527/LEZNED";
       String uName="Lezned";
       String pass="kimi";
       con = DriverManager.getConnection(host, uName, pass);
       stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
       String sql = "SELECT * FROM APP.CUSTOMER_DATA";
       rs = stmt.executeQuery(sql);
    }catch (SQLException err) {
        JOptionPane.showMessageDialog(MainMenu.this,err + "errro rr");
    }
}
    int account = 1;
    int pin = 1234;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnDeposit = new javax.swing.JButton();
        jbtnWithdrawal = new javax.swing.JButton();
        jbtnChangeP = new javax.swing.JButton();
        jbtnBalance = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jbtnDeposit.setText("Deposit");
        jbtnDeposit.setPreferredSize(new java.awt.Dimension(107, 23));
        jbtnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDepositActionPerformed(evt);
            }
        });

        jbtnWithdrawal.setText("Withdrawal");
        jbtnWithdrawal.setPreferredSize(new java.awt.Dimension(107, 23));
        jbtnWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWithdrawalActionPerformed(evt);
            }
        });

        jbtnChangeP.setText("Change Pin");
        jbtnChangeP.setMinimumSize(new java.awt.Dimension(107, 23));
        jbtnChangeP.setPreferredSize(new java.awt.Dimension(107, 23));
        jbtnChangeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangePActionPerformed(evt);
            }
        });

        jbtnBalance.setText("Balance Inquiry");
        jbtnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBalanceActionPerformed(evt);
            }
        });

        jbtnExit.setText("Exit");
        jbtnExit.setPreferredSize(new java.awt.Dimension(107, 23));
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(jbtnChangeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnWithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnBalance)))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnChangeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnWithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBalance))
                .addGap(41, 41, 41)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBalanceActionPerformed
        int bal;
        try {
            rs.next();
            bal = rs.getInt("BALANCE");
            JOptionPane.showMessageDialog(this.jbtnBalance,"Your balance is " + bal);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(this, err);
        }
            

    }//GEN-LAST:event_jbtnBalanceActionPerformed

    private void jbtnChangePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangePActionPerformed
        this.dispose();
        new ChangePass().setVisible(true);
    }//GEN-LAST:event_jbtnChangePActionPerformed

    private void jbtnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDepositActionPerformed
        this.dispose();
        new Deposit().setVisible(true);
    }//GEN-LAST:event_jbtnDepositActionPerformed

    private void jbtnWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWithdrawalActionPerformed
        this.dispose();
        new Withdrawal().setVisible(true);
    }//GEN-LAST:event_jbtnWithdrawalActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnBalance;
    private javax.swing.JButton jbtnChangeP;
    private javax.swing.JButton jbtnDeposit;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnWithdrawal;
    // End of variables declaration//GEN-END:variables
}
